Admin/Admin/Models/LopHocPhan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Admin.Models
{
    public class LopHocPhan
    {
        [Key]
        public int MaLopHP { get; set; }
        [Required]
        [Display(Name = "Tên lớp học phần")]
        public string TenLopHP { get; set; }
        public int MaGiangVien { get; set; }
        [Required]
        public int MaMonHoc { get; set; }
        public List<CTLopHP> CTLopHPs { get; set; }
        public int MaLop { get; set; }
        [Display(Name = "Trạng thái")]
        public int TrangThai { get; set; }

       

    }
}

Admin/Admin/Controllers/LopHocPhansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Admin.Data;
using Admin.Models;
using Admin.ModelJoin;

namespace Admin.Controllers
{
    public class LopHocPhansController : Controller
    {
        private readonly ProjectContext _context;

        public LopHocPhansController(ProjectContext context)
        {
            _context = context;
        }

        // GET: LopHocPhans
        public ActionResult Index()
        {
            var data = GetListLopHPJoin();

            return View(data);
        }

        // GET: LopHocPhans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var data = GetListLopHPJoin();
            var lopHP = data.FirstOrDefault(x => x.LopHocPhan.MaLopHP == id);
            
            if (id == null)
            {
                return NotFound();
            }

            var lopHocPhan = await _context.LopHocPhans.FirstOrDefaultAsync(m => m.MaLopHP == id);

            if (lopHocPhan == null)
            {
                return NotFound();
            }

            return View(lopHP);
        }

        // GET: LopHocPhans/Create
        public IActionResult Create()
        {
            SetSelectListLoai();
            return View();
        }

        // POST: LopHocPhans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaLopHP,TenLopHP,MaGiangVien,MaMonHoc,MaLop")] LopHocPhan lopHocPhan)
        {
            if (ModelState.IsValid)
            {
                var checkDuplicate = _context.LopHocPhans
                    .FirstOrDefault(item => item.MaLop == lopHocPhan.MaLop && item.MaMonHoc == lopHocPhan.MaMonHoc && item.TrangThai == 1);
                if (checkDuplicate == null)
                {
                    lopHocPhan.TrangThai = 1;
                    _context.Add(lopHocPhan);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                
                ModelState.AddModelError("", "Lớp học phần đã tồn tại");

                SetSelectListLoai();
            }
            return View(lopHocPhan);
        }

        // GET: LopHocPhans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            SetSelectListLoai();
            if (id == null)
            {
                return NotFound();
            }

            var lopHocPhan = await _context.LopHocPhans.FindAsync(id);
            if (lopHocPhan == null)
            {
                return NotFound();
            }
            return View(lopHocPhan);
        }

        // POST: LopHocPhans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaLopHP,TenLopHP,MaGiangVien,MaMonHoc,MaLop,TrangThai")] LopHocPhan lopHocPhan)
        {
            if (id != lopHocPhan.MaLopHP)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    lopHocPhan.TrangThai = 1;
                    _context.Update(lopHocPhan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LopHocPhanExists(lopHocPhan.MaLopHP))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lopHocPhan);
        }

        // GET: LopHocPhans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lopHocPhan = await _context.LopHocPhans
                .FirstOrDefaultAsync(m => m.MaLopHP == id);
            if (lopHocPhan == null)
            {
                return NotFound();
            }

            return View(lopHocPhan);
        }

        // POST: LopHocPhans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lopHocPhan = await _context.LopHocPhans.FindAsync(id);
            lopHocPhan.TrangThai = 0;
            _context.Update(lopHocPhan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string inputKeyword)
        {
            var data = GetListLopHPJoin();

            var lopHPs = data.Where(x => x.LopHocPhan.TenLopHP.Contains(inputKeyword) ||
                                         x.MonHoc.TenMonHoc.Contains(inputKeyword) ||
                                         x.GiangVien.TenGiangVien.Contains(inputKeyword) ||
                                         x.Lop.TenLop.Contains(inputKeyword));

            if (inputKeyword == null)
            {
                return View(data);
            }

            return View(lopHPs);
        }
        private bool LopHocPhanExists(int id)
        {
            return _context.LopHocPhans.Any(e => e.MaLopHP == id);
        }

        private IEnumerable<LopHocPhanJoinGiangVien> GetListLopHPJoin()
        {
            List<LopHocPhan> lopHocPhans = _context.LopHocPhans.ToList();
            List<GiangVien> giangViens = _context.GiangViens.ToList();
            List<MonHoc> monHocs = _context.MonHocs.ToList();
            List<Lop> lops = _context.Lops.ToList();

            var data = from lhp in lopHocPhans
                       join gv in giangViens on lhp.MaGiangVien equals gv.MaGiangVien
                       join l in lops on lhp.MaLop equals l.MaLop
                       join mh in monHocs on lhp.MaMonHoc equals mh.MaMonHoc
                       select new LopHocPhanJoinGiangVien
                       {
                           LopHocPhan = lhp,
                           GiangVien = gv,
                           Lop = l,
                           MonHoc = mh
                       };

            return data;
        }

        private void SetSelectListLoai()
        {
            ViewData["LopId"] = new SelectList(_context.Lops.Where(item => item.TrangThai).ToList(), "MaLop", "TenLop");
            ViewData["MonHocId"] = new SelectList(_context.MonHocs.Where(item => item.TrangThai).ToList(), "MaMonHoc", "TenMonHoc");
            ViewData["GiangVienId"] = new SelectList(_context.GiangViens.Where(item => item.TrangThai).ToList(), "MaGiangVien", "TenGiangVien");
        }
    }
}

Admin/Admin/Views/LopHocPhans/Create.cshtml
@model Admin.Models.LopHocPhan

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var dataLop = ViewData["DataLop"];
    var dataGiangVien = ViewData["DataGiangVien"];
}

<h1>Tạo mới</h1>

<h4>Lớp học phần</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="lopHocPhan">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenLopHP" class="control-label"></label>
                <input asp-for="TenLopHP" id="TenLopHP" class="form-control" />
                <span asp-validation-for="TenLopHP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Giảng viên</label>
                <select asp-for="MaGiangVien" class="form-control" asp-items="ViewBag.GiangVienId">
                </select>
                <span asp-validation-for="TenLopHP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Môn học</label>
                <select asp-for="MaMonHoc" class="form-control" asp-items="ViewBag.MonHocId">
                </select>
                <span asp-validation-for="TenLopHP" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="MaLop" class="control-label">Lớp</label>

                <select asp-for="MaLop" class="form-control" asp-items="ViewBag.LopId">
                </select>
                <span asp-validation-for="TenLopHP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách</a>
</div>

<script>
    $().ready(function () {
        $("#lopHocPhan").validate({
            onfocusout: false,
            onkeyup: false,
            onclick: false,
            rules: {
                "TenLopHP": {
                    required: true,
                },
            },
            messages:
            {
                "TenLopHP": {
                    required: "Tên lớp học phần không được bỏ trống"

                },
            }
        });
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Admin/Admin/Views/LopHocPhans/Delete.cshtml
@model Admin.Models.LopHocPhan

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xóa</h1>

<h3>Bạn có chắc chắn muốn xóa?</h3>
<div>
    <h4>Lớp học phần</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenLopHP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenLopHP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaGiangVien)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaGiangVien)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaMonHoc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaMonHoc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaLop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaLopHP" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Danh sách</a>
    </form>
</div>

Admin/Admin/Views/LopHocPhans/Details.cshtml
@model Admin.ModelJoin.LopHocPhanJoinGiangVien

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Chi tiết</h1>

<div>
    <h4>Lớp học phần</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LopHocPhan.TenLopHP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LopHocPhan.TenLopHP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GiangVien.TenGiangVien)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiangVien.TenGiangVien)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonHoc.TenMonHoc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MonHoc.TenMonHoc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lop.TenLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lop.TenLop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LopHocPhan.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LopHocPhan.TrangThai)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LopHocPhan.MaLopHP">Sửa</a> |
    <a asp-action="Index">Danh sách</a>
</div>

Admin/Admin/Views/LopHocPhans/Edit.cshtml
@model Admin.Models.LopHocPhan

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Chỉnh sửa</h1>

<h4>Lớp học phần</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="lopHocPhan">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaLopHP" />
            <div class="form-group">
                <label asp-for="TenLopHP" class="control-label"></label>
                <input asp-for="TenLopHP" id="TenLopHP" class="form-control" />
                <span asp-validation-for="TenLopHP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Giảng viên</label>
                <select asp-for="MaGiangVien" class="form-control" asp-items="ViewBag.GiangVienId">
                </select>
                <span asp-validation-for="MaGiangVien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Môn học</label>
                <select asp-for="MaMonHoc" class="form-control" asp-items="ViewBag.MonHocId">
                </select>
                <span asp-validation-for="MaMonHoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label"> Lớp</label>
                <select asp-for="MaLop" class="form-control" asp-items="ViewBag.LopId">
                </select>
                <span asp-validation-for="MaLop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách</a>
</div>

<script>
    $().ready(function () {
        $("#lopHocPhan").validate({
            onfocusout: false,
            onkeyup: false,
            onclick: false,
            rules: {
                "TenLopHP": {
                    required: true,
                },
            },
            messages:
            {
                "TenLopHP": {
                    required: "Tên lớp học phần không được bỏ trống"

                },
            }
        });
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Admin/Admin/Views/LopHocPhans/Index.cshtml
@model IEnumerable<Admin.ModelJoin.LopHocPhanJoinGiangVien>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Trang chủ Lớp học phần</h1>

<p>
    <a asp-action="Create">Tạo mới</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LopHocPhan.TenLopHP)
            </th>
            <th>
               Tên giảng viên
            </th>
            <th>
                Tên môn học
            </th>
            <th>
                Tên lớp
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LopHocPhan.TrangThai)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LopHocPhan.TenLopHP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GiangVien.TenGiangVien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MonHoc.TenMonHoc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lop.TenLop)
                </td>
                <td>
                    @if (item.LopHocPhan.TrangThai == 1)
                    {
                        <button type="submit" class="btn btn-success">Hoạt động</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-secondary">Không hoạt động</button>
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.LopHocPhan.MaLopHP">Sửa</a> |
                    <a asp-action="Details" asp-route-id="@item.LopHocPhan.MaLopHP">Chi tiết</a> |
                    <a asp-action="Delete" asp-route-id="@item.LopHocPhan.MaLopHP">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('.table').DataTable();
    });
</script>

Admin/Admin/Views/LopHocPhans/Search.cshtml
@model IEnumerable<Admin.ModelJoin.LopHocPhanJoinGiangVien>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Search</h1>
<div class="topnav">
    <a asp-action="Create">Create New</a>
    <div class="float-right-bar">
        @using (Html.BeginForm("Search", "LopHocPhans", FormMethod.Post))
        {
            <input id="inputKeyword" name="inputKeyword" type="text" placeholder="Search.." />
            <a asp-action="Search">
                <input type="submit" asp-action="Search" value="Search" />
            </a>
        }
    </div>
</div>

@if (!Model.Any())
{
    <h3>Không tìm thấy kết quả</h3>
}
else
{
    
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.LopHocPhan.TenLopHP)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LopHocPhan.MaGiangVien)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MonHoc.MaMonHoc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Lop.MaLop)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LopHocPhan.TrangThai)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.LopHocPhan.TenLopHP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GiangVien.TenGiangVien)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MonHoc.TenMonHoc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Lop.TenLop)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LopHocPhan.TrangThai)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.LopHocPhan.MaLopHP">Sửa</a> |
                        <a asp-action="Details" asp-route-id="@item.LopHocPhan.MaLopHP">Chi tiết</a> |
                        <a asp-action="Delete" asp-route-id="@item.LopHocPhan.MaLopHP">Xóa</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}