Admin/Admin/Models/SinhVien.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Admin.Models
{
    public class SinhVien
    {
        [Key]
        public int MaSV { get; set; }
        [Display(Name = "Tên sinh viên")]
        [Required]
        public string TenSV { get; set; }
        [Display(Name = "Địa chỉ")]
        [Required]
        public string DiaChi { get; set; }
        [Display(Name = "Số điện thoại")]
        [Required]
        public string SoDienThoai { get; set; }
        [Required]
        public string Email { get; set; }
        [Display(Name = "Trạng thái")]
        public bool TrangThai { get; set; }
        [Display(Name = "Loại")]
        public string Type { get; set; }
        public List<CTLopHP> CTLopHPs { get; set; }
        public int Lop { get; set; }
        public int MaTaiKhoan { get; set; }
        public List<CTKetQua> CTKetQuas { get; set; }
    }
}

Admin/Admin/Controllers/SinhViensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Admin.Data;
using Admin.Models;
using Admin.ModelJoin;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Admin.Controllers
{
    public class SinhViensController : Controller
    {
        private readonly ProjectContext _context;
        private readonly IWebHostEnvironment hostingEnvironment;

        public SinhViensController(ProjectContext context, IWebHostEnvironment environment)
        {
            _context = context;
            hostingEnvironment = environment;
        }

        // GET: SinhViens
        public async Task<IActionResult> Index()
        {
            var data = GetSinhVienJoins();

            return View(data);
        }

        // GET: SinhViens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            List<TaiKhoan> taiKhoans = _context.TaiKhoans.ToList();
            List<SinhVien> sinhViens = _context.SinhViens.ToList();
            List<Lop> lops = _context.Lops.ToList();

            var data = GetSinhVienJoins();

            if (id == null)
            {
                return NotFound();
            }

            var sinhVien = data
                .FirstOrDefault(m => m.SinhVien.MaSV == id);
            if (sinhVien == null)
            {
                return NotFound();
            }

            return View(sinhVien);
        }

        // GET: SinhViens/Create
        public IActionResult Create()
        {
            var tkSV = _context.TaiKhoans.Where(u => u.LoaiTaiKhoan == 2).ToList();
            var existedTKSV = _context.TaiKhoans
                .Join(
                _context.SinhViens,
                tk => tk.Id,
                sv => sv.MaTaiKhoan,
                (tk, sv) => new
                {
                    tkId = tk.Id,
                });

            ViewData["LopId"] = new SelectList(_context.Lops.Where(u => u.TrangThai).ToList(), "MaLop", "TenLop");
            ViewData["TaiKhoanId"] = new SelectList(tkSV.Where(u => !existedTKSV.Any(item => item.tkId == u.Id)), "Id", "UserName");

            return View();
        }

        // POST: SinhViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSV,TenSV,DiaChi,SoDienThoai,Email,TrangThai,Type,Lop,MaTaiKhoan")] SinhVien sinhVien)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sinhVien);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sinhVien);
        }

        // GET: SinhViens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["LopId"] = new SelectList(_context.Lops.Where(u => u.TrangThai).ToList(), "MaLop", "TenLop");

            if (id == null)
            {
                return NotFound();
            }

            var sinhVien = await _context.SinhViens.FindAsync(id);
            ViewData["TaiKhoanId"] = new SelectList(_context.TaiKhoans.Where(u => u.Id == sinhVien.MaTaiKhoan), "Id", "UserName");

            if (sinhVien == null)
            {
                return NotFound();
            }
            return View(sinhVien);
        }

        // POST: SinhViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaSV,TenSV,DiaChi,SoDienThoai,Email,TrangThai,Type,Lop,MaTaiKhoan")] SinhVien sinhVien)
        {
            if (id != sinhVien.MaSV)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sinhVien);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SinhVienExists(sinhVien.MaSV))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sinhVien);
        }

        // GET: SinhViens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sinhVien = await _context.SinhViens
                .FirstOrDefaultAsync(m => m.MaSV == id);
            if (sinhVien == null)
            {
                return NotFound();
            }

            return View(sinhVien);
        }

        // POST: SinhViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sinhVien = await _context.SinhViens.FindAsync(id);
            sinhVien.TrangThai = false;
            _context.Update(sinhVien); await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult ImportFile()
        {
            ViewData["LopId"] = new SelectList(_context.Lops.Where(u => u.TrangThai).ToList(), "MaLop", "TenLop");
            return View(new SinhVien());
        }

        [HttpPost]
        public ActionResult ImportFile(IFormFile postedFile, [Bind("Lop")] SinhVien sinhVien)
        {
            if (postedFile != null)
            {
                string fileExtension = Path.GetExtension(postedFile.FileName);

                //Validate uploaded file and return error.
                if (fileExtension != ".csv")
                {
                    ViewBag.Message = "Vui lòng chọn file có định dạng .csv";
                    ViewData["LopId"] = new SelectList(_context.Lops.Where(u => u.TrangThai).ToList(), "MaLop", "TenLop");
                    return View();
                }

                var sinhViens = new List<SinhVien>();
                List<string> lstFailedUsername = new List<string>();
                using (var sreader = new StreamReader(postedFile.OpenReadStream()))
                {
                    //First line is header. If header is not passed in csv then we can neglect the below line.
                    string[] headers = sreader.ReadLine().Split(',');
                    //Loop through the records
                    while (!sreader.EndOfStream)
                    {
                        string[] rows = sreader.ReadLine().Split(',');
                        string username = rows[5].ToString();
                        if (IsExistsUsername(username))
                        {
                            lstFailedUsername.Add(username);
                            continue;
                        }

                        TaiKhoan tkCreated = CreateTKSinhVien(username);

                        if (tkCreated == null)
                        {
                            lstFailedUsername.Add(username);
                            continue;
                        }

                        sinhViens.Add(new SinhVien
                        {
                            TenSV = rows[0].ToString(),
                            DiaChi = rows[1].ToString(),
                            SoDienThoai = rows[2].ToString(),
                            Email = rows[3].ToString(),
                            Lop = sinhVien.Lop,
                            MaTaiKhoan = tkCreated.Id,
                            TrangThai = true,
                        });
                    }

                    _context.AddRange(sinhViens);
                    _context.SaveChanges();
                }

                var data = GetSinhVienJoins();

                return RedirectToAction("Index", data);
            }
            else
            {
                ViewBag.Message = "Vui lòng chọn file!";
            }
            ViewData["LopId"] = new SelectList(_context.Lops.Where(u => u.TrangThai).ToList(), "MaLop", "TenLop");
            return View();
        }

        private bool SinhVienExists(int id)
        {
            return _context.SinhViens.Any(e => e.MaSV == id);
        }

        private IEnumerable<SinhVienJoin> GetSinhVienJoins()
        {
            List<TaiKhoan> taiKhoans = _context.TaiKhoans.ToList();
            List<SinhVien> sinhViens = _context.SinhViens.ToList();
            List<Lop> lops = _context.Lops.ToList();

            var data = from sv in sinhViens
                       join tk in taiKhoans on sv.MaTaiKhoan equals tk.Id
                       join l in lops on sv.Lop equals l.MaLop
                       select new SinhVienJoin
                       {
                           SinhVien = sv,
                           TaiKhoan = tk,
                           Lop = l
                       };

            var dataWithoutTK = from sv in sinhViens
                                where sv.MaTaiKhoan == 0
                                select new SinhVienJoin
                                {
                                    SinhVien = sv,
                                };
            var result = data.Union(dataWithoutTK);
            return result;
        }

        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);

Admin/Admin/Views/SinhViens/Create.cshtml
@model Admin.Models.SinhVien

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tạo mới</h1>

<h4>Sinh viên</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="SinhVien">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenSV" class="control-label"></label>
                <input asp-for="TenSV" id="TenSV" class="form-control" />
                <span asp-validation-for="TenSV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi"id="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai"id="SoDienThoai"  class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" id="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="TrangThai" /> @Html.DisplayNameFor(model => model.TrangThai)
                </label>
            </div>
            <div class="form-group">

                <label asp-for="Lop" class="control-label">Tên Lớp</label>

                <select asp-for="Lop" id="Lop" class="form-control" asp-items="ViewBag.LopId">
                </select>
            </div>
            <div class="form-group">
                <label class="control-label"> Tài khoản</label>
                <select asp-for="MaTaiKhoan" id="MaTaiKhoan"  class="form-control" asp-items="ViewBag.TaiKhoanId">
                </select>
                <span asp-validation-for="MaTaiKhoan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách</a>
</div>

<script>
    $().ready(function () {
        $("#SinhVien").validate({
            onfocusout: false,
            onkeyup: false,
            onclick: false,
            rules: {
                "TenSV": {
                    required: true,
                },
                "DiaChi":
                {
                    required: true
                },
                "Email":
                {
                    required:true
                },
                "SoDienThoai":
                {
                    required: true
                },
                "Lop":
                {
                    required: true
                },
                "MaTaiKhoan":
                {
                    required : true
                }
            },
            messages:
            {
                "TenSV": {
                    required: "Tên sinh viên không được bỏ trống"

                },
                "DiaChi":
                {
                    required: "Địa chỉ không được bỏ trống"
                },
                "Email":
                {
                    required: "Email không được bỏ trống"
                },
                "SoDienThoai":
                {
                    required: "Số điện thoại không được bỏ trống"
                },
                "Lop":
                {
                    required: "Lớp không được bỏ trống"
                },
                "MaTaiKhoan":
                {
                    required: "Tài khoản  đúng không được bỏ trống"
                }
            }
        });
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Admin/Admin/Views/SinhViens/Delete.cshtml
@model Admin.Models.SinhVien

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xóa</h1>

<h3>Bạn có chắc chắn muốn xóa?</h3>
<div>
    <h4>Sinh viên</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenSV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenSV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDienThoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangThai)
        </dd> 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaTaiKhoan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaTaiKhoan)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaSV" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Danh sách</a>
    </form>
</div>

Admin/Admin/Views/SinhViens/Details.cshtml
@model Admin.ModelJoin.SinhVienJoin

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Chi tiết</h1>

<div>
    <h4>Sinh viên</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SinhVien.TenSV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SinhVien.TenSV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SinhVien.DiaChi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SinhVien.DiaChi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SinhVien.SoDienThoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SinhVien.SoDienThoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SinhVien.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SinhVien.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SinhVien.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SinhVien.TrangThai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lop.TenLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lop.TenLop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaiKhoan.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaiKhoan.UserName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SinhVien.MaSV">Sửa</a> |
    <a asp-action="Index">Danh sách</a>
</div>

Admin/Admin/Views/SinhViens/Edit.cshtml
@model Admin.Models.SinhVien

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Chỉnh sửa</h1>

<h4>Sinh viên</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="SinhVien">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaSV" />
            <div class="form-group">
                <label asp-for="TenSV" class="control-label"></label>
                <input asp-for="TenSV" id="TenSV" class="form-control" />
                <span asp-validation-for="TenSV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" id="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" id="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" id="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="TrangThai" /> @Html.DisplayNameFor(model => model.TrangThai)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Lop" class="control-label"></label>
                <select asp-for="Lop" id="Lop" class="form-control" asp-items="ViewBag.LopId">
                </select>
                <span asp-validation-for="Lop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tài khoản</label>
                <select asp-for="MaTaiKhoan" id="MaTaiKhoan" class="form-control" asp-items="ViewBag.TaiKhoanId" readonly="">
                </select>
                <span asp-validation-for="MaTaiKhoan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách</a>
</div>

<script>
    $().ready(function () {
        $("#SinhVien").validate({
            onfocusout: false,
            onkeyup: false,
            onclick: false,
            rules: {
                "TenSV": {
                    required: true,
                },
                "DiaChi":
                {
                    required: true
                },
                "Email":
                {
                    required:true
                },
                "SoDienThoai":
                {
                    required: true
                },
                "Lop":
                {
                    required: true
                },
                "MaTaiKhoan":
                {
                    required : true
                }
            },
            messages:
            {
                "TenSV": {
                    required: "Tên sinh viên không được bỏ trống"

                },
                "DiaChi":
                {
                    required: "Địa chỉ không được bỏ trống"
                },
                "Email":
                {
                    required: "Email không được bỏ trống"
                },
                "SoDienThoai":
                {
                    required: "Số điện thoại không được bỏ trống"
                },
                "Lop":
                {
                    required: "Lớp không được bỏ trống"
                },
                "MaTaiKhoan":
                {
                    required: "Tài khoản  đúng không được bỏ trống"
                }
            }
        });
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Admin/Admin/Views/SinhViens/ImportFile.cshtml
@model Admin.Models.SinhVien

@{
    ViewData["Title"] = "ImportFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nhập danh sách sinh viên</h1>
@using (Html.BeginForm("ImportFile", "SinhViens", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="form-group">
    <label class="control-label">Chọn file</label>
    <input type="file" id="postedFile" name="postedFile" class="form-control" accept=".csv" />
</div>

    <div class="form-group">
        <div class="form-group">

            <label asp-for="Lop" class="control-label">Tên Lớp</label>

            <select asp-for="Lop" id="Lop" class="form-control" asp-items="ViewBag.LopId">
            </select>
        </div>
        <div class="form-group">
            <br />
            <input type="submit" title="Upload" value="Upload" class="btn btn-primary" />
        </div>
    </div>
    <div class="form-group">

        <div class="col-md-offset-3 col-md-10">
            <br />
            <span style="color:red;">
                @ViewBag.Message
            </span>
        </div>
    </div>
}

Admin/Admin/Views/SinhViens/Index.cshtml
@model IEnumerable<Admin.ModelJoin.SinhVienJoin>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Trang chủ Sinh viên</h1>

<p>
    <a asp-action="Create">Tạo mới</a><br />
    <a asp-action="ImportFile">Nhập danh sách sinh viên</a>
</p>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SinhVien.TenSV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SinhVien.DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SinhVien.SoDienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SinhVien.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SinhVien.TrangThai)
            </th>
            <th>
                Lớp
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaiKhoan.UserName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SinhVien.TenSV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SinhVien.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SinhVien.SoDienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SinhVien.Email)
            </td>
            <td>
                @if (item.SinhVien.TrangThai)
                {
                    <button type="button" class="btn btn-success">Hoạt động</button>
                }
                else
                {
                    <button type="button" class="btn btn-secondary">Không hoạt động</button>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lop.TenLop)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaiKhoan.UserName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SinhVien.MaSV">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.SinhVien.MaSV">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.SinhVien.MaSV">Xóa</a>
            </td>
        </tr>
}
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $('.table').DataTable();
    });
</script>